apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb1-pv
  namespace: learnerreport-database
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
