apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.backend.namespace }}
type: Opaque
data:
  ATLAS_URI: {{ .Values.backend.secrets.ATLAS_URI | b64enc }}
  HASH_KEY: {{ .Values.backend.secrets.HASH_KEY | b64enc }}
  JWT_SECRET_KEY: {{ .Values.backend.secrets.JWT_SECRET_KEY | b64enc }}
