apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-servicelr
  namespace: {{ .Values.backend.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-servicelr
  namespace: {{ .Values.frontend.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP